In [3]:
import pandas as pd
import time

In [4]:
s_time = time.time()
rawdata = pd.read_csv('xnym-bbo-cl-fut-20200312-r-00065.csv', names=['RawData'], header=None)
e_time = time.time()
print("Time:", (e_time-s_time))

Time: 154.0390362739563

In [5]:
rawdata.head()

                                             RawData
0  2020031214001000000005ECL F200400005       000...
1  2020031214001000000015ECL F200400005       000...
2  2020031214001000000015ECL F200400024       000...
3  2020031216504224503584ECL F200400001       000...
4  2020031216504224503584ECL F200400001       000...

In [6]:
rawdata.shape

(85360646, 1)

In [7]:
#dropping most of the raws for the sample calculation purpose
rawdata.drop(rawdata.index[100:], axis=0, inplace=True)

In [8]:
format = {'TradeDate': {'start': 1, 'end': 8, 'length': 8},
          'TradeTime': {'start': 9, 'end': 14, 'length': 6},
          'TradeSequenceNumber': {'start': 15, 'end': 22, 'length': 8},
          'SessionIndicator': {'start': 23, 'end': 23, 'length': 1},
          'TickerSymbol': {'start': 24, 'end': 26, 'length': 3},
          'FOIIndicator': {'start': 27, 'end': 27, 'length': 1},
          'DeliveryDate': {'start': 28, 'end': 31, 'length': 4},
          'TradeQuantity': {'start': 32, 'end': 36, 'length': 5},
          'StrikePrice': {'start': 45, 'end': 51, 'length': 7},
          'StrikePriceDecimalLocator': {'start': 52, 'end': 52, 'length': 1},
          'Ask/BidType': {'start': 53, 'end': 53, 'length': 1},
          'IndicativevQuoteType': {'start': 54, 'end': 54, 'length': 1},
          'MarketQuote': {'start': 55, 'end': 55, 'length': 1},
          'Close/OpenType': {'start': 56, 'end': 56, 'length': 1},
          'ValidOpenException': {'start': 57, 'end': 58, 'length': 2},
          'PostClose': {'start': 59, 'end': 59, 'length': 1},
          'CancelCodetype': {'start': 60, 'end': 60, 'length': 1},
          'InsertCodeType': {'start': 61, 'end': 61, 'length': 1},
          'Fast/LateIndicator': {'start': 62, 'end': 62, 'length': 1},
          'CabinetIndicator': {'start': 63, 'end': 63, 'length': 1},
          'BookIndicator': {'start': 64, 'end': 64, 'length': 1},
          'EntryDate': {'start': 65, 'end': 70, 'length': 6}
          }

In [9]:
for key in format.keys():
    rawdata[key] = rawdata.RawData.str[format[key]["start"]-1:format[key]["end"]]

In [10]:
rawdata.head()

,RawData,TradeDate,TradeTime,TradeSequenceNumber,SessionIndicator,TickerSymbol,FOIIndicator,DeliveryDate,TradeQuantity,StrikePrice,...,MarketQuote,Close/OpenType,ValidOpenException,PostClose,CancelCodetype,InsertCodeType,Fast/LateIndicator,CabinetIndicator,BookIndicator,EntryDate
0,2020031214001000000005ECL F200400005 000...,20200312,140010,00000005,E,CL,F,2004,00005,0004137,...,M,,,,,,,,,200308
1,2020031214001000000015ECL F200400005 000...,20200312,140010,00000015,E,CL,F,2004,00005,0004137,...,M,,,,,,,,,200308
2,2020031214001000000015ECL F200400024 000...,20200312,140010,00000015,E,CL,F,2004,00024,0004165,...,M,,,,,,,,,200308
3,2020031216504224503584ECL F200400001 000...,20200312,165042,24503584,E,CL,F,2004,00001,0003312,...,M,,,,,,,,,200311
4,2020031216504224503584ECL F200400001 000...,20200312,165042,24503584,E,CL,F,2004,00001,0003296,...,M,,,,,,,,,200311

In [12]:
rawdata.to_csv("conversion_result.csv")